# Utilisez l'image WordPress officielle comme base
FROM wordpress:latest

# Définissez les variables d'environnement
ENV WORDPRESS_DB_HOST=db
ENV WORDPRESS_DB_USER=exampleuser
ENV WORDPRESS_DB_PASSWORD=examplepass
ENV WORDPRESS_DB_NAME=exampledb

# Exposez le port du serveur web
EXPOSE 80
