version: '3.1'

services:

  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - wordpress:/var/www/html

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
